# Generated by Django 5.1.4 on 2025-01-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_usermessages_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='ride_type',
        ),
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ride_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.ridetype')),
                ('room', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Base.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
