# Generated by Django 5.1.4 on 2025-01-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_remove_usermessages_ride_type_userlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlisting',
            name='ride_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Hitchhike', 'Hitchhike')], default='Hitchhike', max_length=15),
        ),
        migrations.RemoveField(
            model_name='userlisting',
            name='room',
        ),
        migrations.DeleteModel(
            name='RideType',
        ),
    ]
